image:
  repository: eso001/complete-devops-project
  tag: dbdc524
  pullPolicy: IfNotPresent
service:
  enabled: true
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false